# Generated by Django 3.1.4 on 2020-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201211_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=1, max_length=250, unique=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(),
        ),
    ]
